
all: install

install:
	mkdir -p /opt/program_files/q4os-user-manual/
	mkdir -p /opt/program_files/q4os-user-manual/icons/
	@echo "Copying files ..."
	install ../q4os-user-manual.pdf /opt/program_files/q4os-user-manual/
	install ../files/q4os-user-manual.svg /opt/program_files/q4os-user-manual/icons/
	chmod -R a+r /opt/program_files/q4os-user-manual/
