
all: install

install:
	mkdir -p /opt/program_files/q4os-user-manual/
	@echo "Copying files ..."
	install ../q4os-user-guide.pdf /opt/program_files/q4os-user-manual/
	chmod -R a+r /opt/program_files/q4os-user-manual/
